
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-project2
  namespace: joaojunior
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: joaojunior
