
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: joaojunior
spec:
  selector:
    app: api-container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
