
FROM python:3.9-slim

WORKDIR /app

COPY scripts/train_model.py /app/train_model.py
COPY volumes /home/joaojunior/project2-pv2

RUN pip install pandas fpgrowth_py

CMD ["python3", "/app/train_model.py"]
